### ISSUE TITLE
AOT compilation in .NET 6 failing with ZXing.Net.Bindings.ImageSharp 0.16.9-beta

### ISSUE THREAD

**Issue by thepra** [micjahn/ZXing.Net#371] opened 2021-11-09 12:53 UTC
Here's the console error:
>Failed to load method 0x600010b from 'C:\Users\VOID\Desktop\projects\<redacted>\<redacted>\Client\obj\Release\net6.0\linked\zxing.dll' due to Could not load file or assembly 'System.Drawing.Common, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies..
Mono Ahead of Time compiler - compiling assembly C:\Users\VOID\Desktop\projects\<redacted>\<redacted>\Client\obj\Release\net6.0\linked\zxing.dll
Run with MONO_LOG_LEVEL=debug for more information.
AOT of image zxing.dll failed.

It's kind of strange that its pulling `System.Drawing.Common` in the compilation given that I'm compiling toward WASM which doesn't support that system library. Is this the fault of the package or do I need to setup something to make it skip?

**Comment by micjahn** [comment] 2021-11-17 16:28
Do you have a sample project which I can use to reproduce the error?
I tried to build the whole ZXing project including the bindings with VS 2022. I think I did something wrong because it worked without an error.

**Comment by thepra** [comment] 2021-11-17 19:10
I don't but it should be possible with this in the `client.csprof`
```
<PropertyGroup>
  <RunAOTCompilation>true</RunAOTCompilation>
</PropertyGroup>
```
And starting from this template:
![immagine](https://user-images.githubusercontent.com/7032509/142265928-236d5b8f-512f-4310-b1c3-2598866165f6.png)
Adding the library to the client and setup a InputFile event where you catch it and use the file stream:
```
protected async Task ReadFileQrCode(InputFileChangeEventArgs e)
{
    GetBarcodeFromStreamAsync(e.File.OpenReadStream());
}

async ValueTask<string> GetBarcodeFromStreamAsync(Stream stream)
{
    using (var image = await SixLabors.ImageSharp.Image.LoadAsync<SixLabors.ImageSharp.PixelFormats.Rgba32>(stream))
    {
	var reader = new ZXing.ImageSharp.BarcodeReader<SixLabors.ImageSharp.PixelFormats.Rgba32>();
	var result = reader.Decode(image);
	return result?.Text;
    }
    return default;
}
```

**Comment by micjahn** [comment] 2021-11-17 20:31
How did you add the reference of ZXing.Net to your project? Did you use the nuget package?

I build a small Blazor app and added RunAOTCompilation. I could successfully compile and run the project. I uploaded a barcode image and the result was shown with an alert box.

**Comment by Shtyba** [comment] 2021-11-23 14:37
Hi you should run publish with release if you want to do AOT compilation. Like this https://blog.elmah.io/ahead-of-time-compilation-for-blazor-wasm/. And you may be able to repeat the error.

**Comment by micjahn** [comment] 2021-11-28 14:36
I could reproduce the error. nuget automatically references the zxing.dll for the .netcoreapp3.1 target.
That build includes the reference to system.drawing.common because bitmap support is built-in.
The only workaround I found is the following:
* remove the package reference from you project file `<PackageReference Include="ZXing.Net.Bindings.ImageSharp" Version="0.16.9-beta" />`
* add the following assembly references manually to your Blazor client project:
```
  <ItemGroup>
    <Reference Include="ZXing">
        <HintPath>$(NuGetPackageRoot)zxing.net\0.16.6\lib\netstandard2.1\zxing.dll</HintPath>
    </Reference>
    <Reference Include="ZXing.Net.Bindings.ImageSharp">
        <HintPath>$(NuGetPackageRoot)zxing.net.bindings.imagesharp\0.16.9-beta\lib\netstandard2.1\ZXing.ImageSharp.dll</HintPath>
    </Reference>
    <Reference Include="SixLabors.ImageSharp">
        <HintPath>$(NuGetPackageRoot)sixlabors.imagesharp\1.0.4\lib\netstandard2.1\SixLabors.ImageSharp.dll</HintPath>
    </Reference>
  </ItemGroup>
```

**Comment by thepra** [comment] 2021-11-29 23:58
Seems to work now :)
Should I keep it open for future fix or should I close this issue?

**Comment by micjahn** [comment] 2021-11-30 20:22
Keep it open. Next release will include .net 6.0 support. Then the nuget package should work correctly and I will close this issue.

**Comment by micjahn** [comment] 2021-12-26 16:57
new release with .net 6.0 support is out

**Closed by micjahn** 2021-12-26 16:57 UTC
