### ISSUE TITLE
support for C40 encoding (ecc200 ISO/IEC 16022)

### ISSUE THREAD

**Issue by julienGrd** [micjahn/ZXing.Net#444] opened 2022-09-14 10:02 UTC
Hello guys, and thanks for your library.

For one of my projects i have to generate a datamatrix, and the requirement is to respect the C40 encoding.

I have trouble to find example on that with your library, is there is a way to do that ? 

thanks !

**Comment by micjahn** [comment] 2022-09-14 19:30
Duplicate of #403

**Closed by micjahn** 2022-09-14 19:30 UTC
Labels: duplicate, enhancement
