### ISSUE TITLE
Build with .NET scripting backend in Unity

### ISSUE THREAD

**Issue by ronneke1996** [micjahn/ZXing.Net#85] opened 2018-03-15 14:35 UTC
Hello,

Im building an Unity project with this plugin and it works great.
The only downside is that I need to build my project with .NET as scripting backend because I use Vuforia, but I'm only able to build the project with ZXing.NET if I use L2CPP as scripting backend. 

I get a lot of the same kind of errors, all something like the one below.

``` Reference rewriter: Error: type `System.ComponentModel.TypeConverterAttribute` doesn't exist in target framework. It is referenced from zxing.unity.dll at ZXing.QrCode.QrCodeEncodingOptions.
UnityEngine.Debug:LogError(Object)
PostProcessWinRT:RunReferenceRewriter() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:988)
PostProcessWinRT:Process() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:211)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) ```

Im using:
Unity 2017.3.1p1
ZXing 0.16.2

**Comment by micjahn** [comment] 2018-03-16 05:50
Duplicate of #75 
fixed in next version

**Closed by micjahn** 2018-03-16 05:50 UTC
Labels: duplicate

**Comment by ronneke1996** [comment] 2018-03-16 06:40
Sorry to ask, but do you have an ETA on 0.16.3?

**Comment by micjahn** [comment] 2018-03-18 12:40
Sorry, no. I hope as soon as possible.
